services:
  jupiterhub:
    container_name: jupiterhub 
    build:
      context: .
    image: geekonclick/jupyterhub:tested
    env_file:
      - .env
    environment:
      JUPYTERHUB_ADMIN: admin
      DOCKER_NOTEBOOK_DIR: ${CUSTOM_ROOT_DIR}
    restart: always
    ports:
      - 8020:8020
    volumes:
      - "jupyterhub-data:/data"

volumes:
  jupyterhub-data:
