name: Deploy jupiterhub

on:
  push:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - '.github/**'
  pull_request:
    branches: [master]

env:
  IMAGE_NAME: jupyterhub
  TAG: tested

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
  
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Run tests
      run: echo "tested"